// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Bio       pgtype.Text      `json:"bio"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Video struct {
	ID         int32            `json:"id"`
	Name       string           `json:"name"`
	UploadedBy int32            `json:"uploaded_by"`
	IsActive   pgtype.Bool      `json:"is_active"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
